import "./globals.css";
import {
  CHAMELEON_CONTRACT,
  CHAMELEON_CSS,
  CHAMELEON_JS,
  CHAMELEON_VERSION,
} from "@/lib/chameleon-theme.generated";
import type { Metadata } from "next";
import type { ReactNode } from "react";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "html-editor",
  description: "Local browser-based HTML editor for personal notes",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="ja" data-theme="light" data-chameleon="v1" suppressHydrationWarning>
      <head>
        <meta name="chameleon" content={CHAMELEON_CONTRACT} data-baked={CHAMELEON_VERSION} />
        {/* Same baked theme as saved files (see html-template.ts) so the
            editor UI matches them exactly and works offline. */}
        {/* biome-ignore lint/security/noDangerouslySetInnerHtml: CHAMELEON_CSS is a build-time constant generated by scripts/sync-theme.ts from our own theme repo — not user input. */}
        <style dangerouslySetInnerHTML={{ __html: CHAMELEON_CSS }} />
        {/* biome-ignore lint/security/noDangerouslySetInnerHtml: CHAMELEON_JS is the same build-time constant source as above. */}
        <script dangerouslySetInnerHTML={{ __html: CHAMELEON_JS }} />
      </head>
      <body className="bg-canvas">
        {children}
        <Toaster position="bottom-right" richColors />
      </body>
    </html>
  );
}
