// Sync the Chameleon theme from the local html-chameleon clone into a
// generated TS module (src/lib/chameleon-theme.generated.ts), so saved
// files and the editor UI inline the theme instead of linking the hosted
// copy. Saved files stay self-contained: they render offline, via file://,
// and identically forever — updates are distributed explicitly via
// `pnpm rebake` rather than arriving implicitly over the network.
//
// Usage:
//   pnpm sync-theme [path-to-html-chameleon-clone]
//   CHAMELEON_DIR=/path/to/clone pnpm sync-theme
//
// The clone's `git describe --tags` output becomes CHAMELEON_VERSION and is
// stamped into every saved file as <meta name="chameleon" data-baked="...">.

import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const DEFAULT_CLONE = join(process.env.HOME ?? "~", "MyApps/_chrome/260509-html-chameleon");

const cloneDir = resolve(process.argv[2] ?? process.env.CHAMELEON_DIR ?? DEFAULT_CLONE);
const themeDir = join(cloneDir, "theme/v1");
const outPath = join(import.meta.dirname, "../src/lib/chameleon-theme.generated.ts");

if (!existsSync(join(themeDir, "theme.css"))) {
  console.error(`theme/v1/theme.css not found under: ${cloneDir}`);
  console.error("Pass the html-chameleon clone path as an argument or set CHAMELEON_DIR.");
  process.exit(1);
}

const css = readFileSync(join(themeDir, "theme.css"), "utf8");
const jsRaw = readFileSync(join(themeDir, "theme.js"), "utf8");

// `</style` inside the CSS would terminate the inline <style> block early.
// There is no clean in-CSS escape, so fail loudly and fix it in the source repo.
if (/<\/style/i.test(css)) {
  console.error("theme.css contains '</style' — remove it in html-chameleon first.");
  process.exit(1);
}
// `</script` inside the JS (currently only in the header comment) would
// terminate the inline <script> block early. `<\/script` is inert in HTML and
// harmless inside JS comments/strings, which is the only place it can appear.
const js = jsRaw.replace(/<\/script/gi, "<\\/script");

// v1.0.0 → "1.0.0"; v1.0.0-2-gabc1234 → "1.0.0-2-gabc1234" (commits past tag).
let version: string;
try {
  version = execFileSync("git", ["-C", cloneDir, "describe", "--tags", "--abbrev=7"], {
    encoding: "utf8",
  })
    .trim()
    .replace(/^v/, "");
} catch {
  console.error(`Could not read a version tag from ${cloneDir} — tag it (e.g. v1.0.0) first.`);
  process.exit(1);
}
const major = version.match(/^(\d+)\./)?.[1];
if (!major) {
  console.error(`Unexpected version format: ${version}`);
  process.exit(1);
}

const banner = `// AUTO-GENERATED by scripts/sync-theme.ts — do not edit by hand.
// Source: churin1116/html-chameleon theme/v1 @ ${version}
// Re-run \`pnpm sync-theme\` after updating the html-chameleon clone.
`;

const out = `${banner}
export const CHAMELEON_VERSION = ${JSON.stringify(version)};

// Semver-style update policy stamped into saved files: rebake may move a
// file to any newer version within this major, never across majors.
export const CHAMELEON_CONTRACT = ${JSON.stringify(`^${major}`)};

export const CHAMELEON_CSS = ${JSON.stringify(css)};

export const CHAMELEON_JS = ${JSON.stringify(js)};
`;

writeFileSync(outPath, out);
console.log(
  `Synced chameleon ${version} (${(css.length / 1024).toFixed(1)}KB css + ${(js.length / 1024).toFixed(1)}KB js) → src/lib/chameleon-theme.generated.ts`,
);
